# Approximate mapping of US NANP area codes to a representative city and state.
# Many area codes cover a wider metro region; this maps each code to its
# best-known anchor city for search purposes, not an exact legal boundary.

AREA_CODES = {
    # Northeast
    "212": ("New York", "NY"), "646": ("New York", "NY"), "332": ("New York", "NY"),
    "718": ("New York", "NY"), "347": ("New York", "NY"), "929": ("New York", "NY"), "917": ("New York", "NY"),
    "315": ("Syracuse", "NY"), "680": ("Syracuse", "NY"),
    "518": ("Albany", "NY"), "838": ("Albany", "NY"),
    "585": ("Rochester", "NY"), "716": ("Buffalo", "NY"), "607": ("Binghamton", "NY"),
    "914": ("Yonkers", "NY"), "516": ("Hempstead", "NY"), "631": ("Islip", "NY"), "934": ("Islip", "NY"),
    "845": ("Poughkeepsie", "NY"),
    "201": ("Jersey City", "NJ"), "551": ("Jersey City", "NJ"),
    "609": ("Trenton", "NJ"), "640": ("Trenton", "NJ"),
    "732": ("New Brunswick", "NJ"), "848": ("New Brunswick", "NJ"),
    "856": ("Camden", "NJ"), "862": ("Newark", "NJ"), "973": ("Newark", "NJ"),
    "908": ("Elizabeth", "NJ"),
    "215": ("Philadelphia", "PA"), "267": ("Philadelphia", "PA"), "445": ("Philadelphia", "PA"),
    "412": ("Pittsburgh", "PA"), "878": ("Pittsburgh", "PA"),
    "610": ("Allentown", "PA"), "484": ("Allentown", "PA"), "835": ("Allentown", "PA"),
    "717": ("Harrisburg", "PA"), "223": ("Lancaster", "PA"),
    "570": ("Scranton", "PA"), "272": ("Scranton", "PA"),
    "814": ("Erie", "PA"), "724": ("New Castle", "PA"),
    "617": ("Boston", "MA"), "857": ("Boston", "MA"),
    "339": ("Boston", "MA"), "781": ("Boston", "MA"),
    "413": ("Springfield", "MA"), "508": ("Worcester", "MA"), "774": ("Worcester", "MA"),
    "978": ("Lowell", "MA"), "351": ("Lowell", "MA"),
    "401": ("Providence", "RI"),
    "203": ("Bridgeport", "CT"), "475": ("Bridgeport", "CT"),
    "860": ("Hartford", "CT"), "959": ("Hartford", "CT"),
    "802": ("Burlington", "VT"),
    "603": ("Manchester", "NH"),
    "207": ("Portland", "ME"),

    # South
    "202": ("Washington", "DC"),
    "301": ("Silver Spring", "MD"), "240": ("Silver Spring", "MD"),
    "410": ("Baltimore", "MD"), "443": ("Baltimore", "MD"), "667": ("Baltimore", "MD"),
    "703": ("Arlington", "VA"), "571": ("Arlington", "VA"),
    "757": ("Virginia Beach", "VA"), "804": ("Richmond", "VA"), "434": ("Lynchburg", "VA"), "540": ("Roanoke", "VA"),
    "304": ("Charleston", "WV"), "681": ("Charleston", "WV"),
    "704": ("Charlotte", "NC"), "980": ("Charlotte", "NC"),
    "919": ("Raleigh", "NC"), "984": ("Raleigh", "NC"),
    "336": ("Greensboro", "NC"), "743": ("Greensboro", "NC"),
    "252": ("Greenville", "NC"), "828": ("Asheville", "NC"), "910": ("Fayetteville", "NC"),
    "803": ("Columbia", "SC"), "839": ("Columbia", "SC"),
    "843": ("Charleston", "SC"), "854": ("Charleston", "SC"),
    "864": ("Greenville", "SC"),
    "404": ("Atlanta", "GA"), "678": ("Atlanta", "GA"), "470": ("Atlanta", "GA"), "770": ("Atlanta", "GA"),
    "912": ("Savannah", "GA"), "229": ("Albany", "GA"), "706": ("Augusta", "GA"), "762": ("Augusta", "GA"),
    "305": ("Miami", "FL"), "786": ("Miami", "FL"),
    "954": ("Fort Lauderdale", "FL"), "754": ("Fort Lauderdale", "FL"),
    "561": ("West Palm Beach", "FL"), "321": ("Orlando", "FL"), "407": ("Orlando", "FL"), "689": ("Orlando", "FL"),
    "813": ("Tampa", "FL"), "656": ("Tampa", "FL"), "727": ("St. Petersburg", "FL"),
    "904": ("Jacksonville", "FL"), "850": ("Tallahassee", "FL"), "352": ("Gainesville", "FL"),
    "239": ("Fort Myers", "FL"), "941": ("Sarasota", "FL"), "863": ("Lakeland", "FL"), "386": ("Daytona Beach", "FL"),
    "615": ("Nashville", "TN"), "629": ("Nashville", "TN"),
    "901": ("Memphis", "TN"), "731": ("Jackson", "TN"), "423": ("Chattanooga", "TN"), "865": ("Knoxville", "TN"),
    "502": ("Louisville", "KY"), "606": ("Pikeville", "KY"), "859": ("Lexington", "KY"), "270": ("Bowling Green", "KY"),
    "205": ("Birmingham", "AL"), "659": ("Birmingham", "AL"),
    "251": ("Mobile", "AL"), "334": ("Montgomery", "AL"), "256": ("Huntsville", "AL"), "938": ("Huntsville", "AL"),
    "601": ("Jackson", "MS"), "769": ("Jackson", "MS"), "662": ("Tupelo", "MS"), "228": ("Gulfport", "MS"),
    "501": ("Little Rock", "AR"), "479": ("Fayetteville", "AR"), "870": ("Jonesboro", "AR"),
    "504": ("New Orleans", "LA"), "985": ("Houma", "LA"), "225": ("Baton Rouge", "LA"), "337": ("Lafayette", "LA"), "318": ("Shreveport", "LA"),
    "405": ("Oklahoma City", "OK"), "572": ("Oklahoma City", "OK"), "918": ("Tulsa", "OK"), "539": ("Tulsa", "OK"), "580": ("Lawton", "OK"),
    "210": ("San Antonio", "TX"), "726": ("San Antonio", "TX"),
    "214": ("Dallas", "TX"), "469": ("Dallas", "TX"), "972": ("Dallas", "TX"), "945": ("Dallas", "TX"),
    "281": ("Houston", "TX"), "713": ("Houston", "TX"), "346": ("Houston", "TX"), "832": ("Houston", "TX"),
    "512": ("Austin", "TX"), "737": ("Austin", "TX"),
    "915": ("El Paso", "TX"), "817": ("Fort Worth", "TX"), "682": ("Fort Worth", "TX"),
    "361": ("Corpus Christi", "TX"), "956": ("Laredo", "TX"), "806": ("Lubbock", "TX"), "432": ("Midland", "TX"),
    "325": ("Abilene", "TX"), "254": ("Waco", "TX"), "409": ("Beaumont", "TX"), "903": ("Tyler", "TX"), "430": ("Tyler", "TX"), "936": ("Huntsville", "TX"), "979": ("College Station", "TX"), "830": ("New Braunfels", "TX"), "940": ("Denton", "TX"),

    # Midwest
    "312": ("Chicago", "IL"), "773": ("Chicago", "IL"), "872": ("Chicago", "IL"), "773": ("Chicago", "IL"),
    "847": ("Arlington Heights", "IL"), "224": ("Arlington Heights", "IL"),
    "630": ("Aurora", "IL"), "331": ("Aurora", "IL"),
    "708": ("Cicero", "IL"), "815": ("Rockford", "IL"), "779": ("Rockford", "IL"),
    "217": ("Springfield", "IL"), "309": ("Peoria", "IL"), "618": ("Belleville", "IL"),
    "317": ("Indianapolis", "IN"), "463": ("Indianapolis", "IN"),
    "260": ("Fort Wayne", "IN"), "574": ("South Bend", "IN"), "219": ("Gary", "IN"), "812": ("Evansville", "IN"), "930": ("Evansville", "IN"),
    "313": ("Detroit", "MI"), "248": ("Troy", "MI"), "947": ("Troy", "MI"),
    "734": ("Ann Arbor", "MI"), "586": ("Warren", "MI"), "810": ("Flint", "MI"), "616": ("Grand Rapids", "MI"), "989": ("Saginaw", "MI"), "231": ("Traverse City", "MI"), "906": ("Marquette", "MI"), "517": ("Lansing", "MI"),
    "614": ("Columbus", "OH"), "380": ("Columbus", "OH"),
    "216": ("Cleveland", "OH"), "440": ("Elyria", "OH"), "330": ("Akron", "OH"), "234": ("Akron", "OH"),
    "513": ("Cincinnati", "OH"), "283": ("Cincinnati", "OH"),
    "937": ("Dayton", "OH"), "326": ("Dayton", "OH"), "419": ("Toledo", "OH"), "567": ("Toledo", "OH"), "740": ("Newark", "OH"), "220": ("Newark", "OH"),
    "414": ("Milwaukee", "WI"), "608": ("Madison", "WI"), "715": ("Eau Claire", "WI"), "534": ("Eau Claire", "WI"), "920": ("Green Bay", "WI"), "262": ("Kenosha", "WI"),
    "612": ("Minneapolis", "MN"), "651": ("St. Paul", "MN"), "763": ("Brooklyn Park", "MN"), "952": ("Bloomington", "MN"), "218": ("Duluth", "MN"), "507": ("Rochester", "MN"),
    "515": ("Des Moines", "IA"), "319": ("Cedar Rapids", "IA"), "563": ("Davenport", "IA"), "641": ("Mason City", "IA"), "712": ("Sioux City", "IA"),
    "314": ("St. Louis", "MO"), "557": ("St. Louis", "MO"),
    "816": ("Kansas City", "MO"), "660": ("Sedalia", "MO"), "573": ("Columbia", "MO"), "417": ("Springfield", "MO"),
    "316": ("Wichita", "KS"), "620": ("Hutchinson", "KS"), "785": ("Topeka", "KS"), "913": ("Overland Park", "KS"),
    "402": ("Omaha", "NE"), "531": ("Omaha", "NE"), "308": ("North Platte", "NE"),
    "605": ("Sioux Falls", "SD"), "701": ("Fargo", "ND"), "701": ("Fargo", "ND"),
    "701": ("Fargo", "ND"),

    # West / Mountain
    "303": ("Denver", "CO"), "720": ("Denver", "CO"), "983": ("Denver", "CO"),
    "719": ("Colorado Springs", "CO"), "970": ("Fort Collins", "CO"),
    "801": ("Salt Lake City", "UT"), "385": ("Salt Lake City", "UT"), "435": ("St. George", "UT"),
    "702": ("Las Vegas", "NV"), "725": ("Las Vegas", "NV"), "775": ("Reno", "NV"),
    "602": ("Phoenix", "AZ"), "480": ("Phoenix", "AZ"), "623": ("Phoenix", "AZ"),
    "520": ("Tucson", "AZ"), "928": ("Flagstaff", "AZ"),
    "505": ("Albuquerque", "NM"), "575": ("Las Cruces", "NM"),
    "406": ("Billings", "MT"), "307": ("Cheyenne", "WY"), "208": ("Boise", "ID"), "986": ("Boise", "ID"),

    "206": ("Seattle", "WA"), "253": ("Tacoma", "WA"), "425": ("Bellevue", "WA"), "360": ("Vancouver", "WA"), "564": ("Vancouver", "WA"), "509": ("Spokane", "WA"),
    "503": ("Portland", "OR"), "971": ("Portland", "OR"), "541": ("Eugene", "OR"), "458": ("Eugene", "OR"),
    "907": ("Anchorage", "AK"), "808": ("Honolulu", "HI"),

    # California
    "213": ("Los Angeles", "CA"), "323": ("Los Angeles", "CA"), "310": ("Los Angeles", "CA"), "424": ("Los Angeles", "CA"),
    "818": ("Los Angeles", "CA"), "747": ("Los Angeles", "CA"), "626": ("Pasadena", "CA"),
    "415": ("San Francisco", "CA"), "628": ("San Francisco", "CA"),
    "510": ("Oakland", "CA"), "341": ("Oakland", "CA"),
    "650": ("San Mateo", "CA"), "408": ("San Jose", "CA"), "669": ("San Jose", "CA"),
    "619": ("San Diego", "CA"), "858": ("San Diego", "CA"), "935": ("San Diego", "CA"),
    "916": ("Sacramento", "CA"), "279": ("Sacramento", "CA"),
    "209": ("Stockton", "CA"), "559": ("Fresno", "CA"), "661": ("Bakersfield", "CA"),
    "805": ("Santa Barbara", "CA"), "831": ("Salinas", "CA"), "707": ("Santa Rosa", "CA"),
    "760": ("Oceanside", "CA"), "442": ("Oceanside", "CA"),
    "714": ("Anaheim", "CA"), "657": ("Anaheim", "CA"), "949": ("Irvine", "CA"), "951": ("Riverside", "CA"), "909": ("San Bernardino", "CA"), "925": ("Concord", "CA"), "530": ("Redding", "CA"),
}


def lookup_area_code(area_code):
    """Return (city, state) for a US area code, or (None, None) if unknown."""
    return AREA_CODES.get(area_code, (None, None))
